import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${robotoSans.variable} ${robotoMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {" "}
        <Navbar />
        <main className=" mt-24 ">{children} </main>
        <footer className="w-[90%] mx-auto md:w-[80%] py-4 text-center border-t  my-auto">
          © {new Date().getFullYear()}
          <span className="text-green-800 font-extrabold"> ShopMarket</span>.
          All rights reserved.
        </footer>
      </body>
    </html>
  );
}
